# This file was generated by GoReleaser. DO NOT EDIT.
cask "monday" do
  version "0.1.0"

  on_macos do
    sha256 "ae400f88e800857c273ddf6c338f81858d89ae993de09192d7d68bfd9eb1508c"
    url "https://github.com/JadoJodo/monday/releases/download/v#{version}/monday_#{version}_darwin_all.tar.gz"
  end

  name "monday"
  desc "Automate routine macOS maintenance from one command"
  homepage "https://github.com/JadoJodo/monday"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "monday"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/monday"]
    end
  end

  # No zap stanza required

end
