# This file was generated by GoReleaser. DO NOT EDIT.
cask "monday" do
  version "0.1.01"

  on_macos do
    sha256 "acfd1e9f1892566e4eee8a83d66477577ac0543757ffa939d9bf0b3f08721366"
    url "https://github.com/JadoJodo/monday/releases/download/v#{version}/monday_#{version}_darwin_all.tar.gz"
  end

  name "monday"
  desc "Automate routine macOS maintenance from one command"
  homepage "https://github.com/JadoJodo/monday"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "monday"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/monday"]
    end
  end

  # No zap stanza required

end
