# This file was generated by GoReleaser. DO NOT EDIT.
cask "monday" do
  version "0.1"

  on_macos do
    sha256 "41b9828e3ac28390390d5b84f770f3aafdb3638c2e25312b346155e605358f26"
    url "https://github.com/JadoJodo/monday/releases/download/v#{version}/monday_#{version}_darwin_all.tar.gz"
  end

  name "monday"
  desc "Automate routine macOS maintenance from one command"
  homepage "https://github.com/JadoJodo/monday"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "monday"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/monday"]
    end
  end

  # No zap stanza required

end
