# This file was generated by GoReleaser. DO NOT EDIT.
cask "rundown" do
  version "0.2.0"

  on_macos do
    sha256 "3f096696e22225d48dee8cb0c905bc3e8ae8fd77531df6e0e6da9f998c919f06"
    url "https://github.com/JadoJodo/rundown/releases/download/v#{version}/rundown_#{version}_darwin_all.tar.gz"
  end

  name "rundown"
  desc "Automate routine macOS maintenance from one command"
  homepage "https://github.com/JadoJodo/rundown"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rundown"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rundown"]
    end
  end

  # No zap stanza required

end
