# This file was generated by GoReleaser. DO NOT EDIT.
cask "ynab-mcp" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "73b9cfc861d6dfc6649f33e7d6ef22c5274908a3390b19934b7ce2986990031a"
      url "https://github.com/JadoJodo/ynab-mcp/releases/download/v#{version}/ynab-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "603e950e9ad461f94c4bb3be4fc1321820b6962d7388dc70728c5644a557ecbc"
      url "https://github.com/JadoJodo/ynab-mcp/releases/download/v#{version}/ynab-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dccf4a176639bc0af570a4c2a8eef09ff28647b812f0d7da409e1e181a6589b2"
      url "https://github.com/JadoJodo/ynab-mcp/releases/download/v#{version}/ynab-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e48b031686d7cdb5152de0c54a011ebbe6f7bd48cf9a6e06af902c344b1e2008"
      url "https://github.com/JadoJodo/ynab-mcp/releases/download/v#{version}/ynab-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ynab-mcp"
  desc "MCP server for YNAB (You Need A Budget)"
  homepage "https://github.com/JadoJodo/ynab-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ynab-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ynab-mcp"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    ynab-mcp requires a YNAB_API_TOKEN environment variable set in your
    MCP client config. Get a token at https://app.ynab.com/settings/developer.
  EOS
end
